### ISSUE TITLE
Universal selector is now allowed

### ISSUE THREAD

**Issue by jpettitt** [tinovyatkin/stylelint-config-amp#1]
https://github.com/ampproject/amphtml/pull/3375

**Comment by tinovyatkin** [comment]
Thank you for update! Not sure however, if I should update faster than official documentation at https://www.ampproject.org/docs/guides/responsive/style_pages as well as official validator (that doing bad job anyway, allowing `transition: all` on official website). Do you think we should follow Github issue?
